site_name: CNChess Documentation
site_description: Documentation for the CoreXY automated chess board.
use_directory_urls: false
docs_dir: docs_md           # Source docs directory
site_dir: docs     # Output directory (cannot be inside docs_dir)

nav:
  - Home: index.md
  - Game Engine: game_engine.md
  - Hardware Control: hardware_control.md
  - Vision System: vision_system.md
  - Communication Layer: communication.md
  - User Interface: user_interface.md

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: amber
  features:
    - navigation.tabs 
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [python] 
